# Generated by Django 3.1.7 on 2021-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purpose',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
