# Generated by Django 3.1.7 on 2021-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
